### ISSUE TITLE
BC Break on v1.0.4

### ISSUE THREAD

**Issue by Taluu** [Wisembly/intercom-php#2]
The [semantic versionning](http://semver.org) is not respected [between v1.0.3 and v1.0.4](https://github.com/Wisembly/intercom-php/compare/v1.0.3...v1.0.4) ; it may hurt a little if you want to update the library.

Two solutions ;
- Ensure BC Break (using a ghost class like `Event\Event` which extends `Object\Event`
- Tag another major release (2.x, but that's too soon)
- solution 1 + tag 1.1 (as this is not really just a bugfix)

My favourite being solution number 3.

**Comment by rgazelot** [comment]
It was heard ;)
