### ISSUE TITLE
Add some example to the README

### ISSUE THREAD

**Issue by cossou** [Wisembly/intercom-php#4]
Hi, 

could you write a couple of examples on how to use this package?

example:

``` php
$gz = new GuzzleHttp\Client;
$ic = new Intercom\Client('APP-ID', 'API-KEY', $gz);
$event = new Intercom\Object\Event('sent-message', 'USER-ID');
$ic->createEvent($event);
```

Thanks

**Comment by rgazelot** [comment]
Hi,

We are working on this new library and a stable version will come out next week with a complete documentation. 

Thanks and stay tuned ;)

**Comment by cossou** [comment]
:+1:
