### ISSUE TITLE
Conversations

### ISSUE THREAD

**Issue by cossou** [Wisembly/intercom-php#7]
Hi Rémy,

I just did a basic Conversation methods for Intercom. 
It's still messy and I'm not sure how to implement. 
Right now I just return the `$response->json();` array.

Can you take a look and give me some advise? Move everything to a new Class? 

https://github.com/cossou/intercom-php/blob/master/lib/Intercom/Client/User.php#L136-L372

**Comment by guillaumepotier** [comment]
Hi there, great start!

You should rather open a PR instead of an issue, it would be much easier to review your code and make comments!

**Comment by cossou** [comment]
Hi Guilliaum,

I will do that! We continue the discussion there!
